apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: authmicroservice-app
  name: authmicroservice-pod
spec:
  selector:
    matchLabels:
      app: authmicroservice-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: authmicroservice-app
    spec:
      volumes:
      - name: sslcertificate
        configMap:
          name: sslconfig
      containers:
      - name: authmicroservice
        image: vlogp/authmicroservice:development
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
               name: envconfig
        volumeMounts:
        - mountPath: /https/aspnetapp.pfx
          name: sslcertificate
          subPath: aspnetapp.pfx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: 
           requests:
                memory: "64Mi"
                cpu: "50m"
           limits:
                memory: "256Mi"
                cpu: "500m"