apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Certificate for Kestrel
configMapGenerator:
- name: sslconfig
  files: 
  - ./Content/https/aspnetapp.pfx
- name: envconfig 
  literals:
  - ASPNETCORE_ENVIRONMENT=Development
  - ASPNETCORE_Kestrel__Certificates__Default__Password="12345"
  - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  - ASPNETCORE_URLS=https://+:443;http://+:80
 
resources:
- ./ProductMicroservice/ProductMicroservice/Configurations/Kubernetes/deployment.yaml
- ./ProductMicroservice/ProductMicroservice/Configurations/Kubernetes/service.yaml
- ./ReportMicroservice/ReportMicroservice/Configurations/Kubernetes/deployment.yaml
- ./ReportMicroservice/ReportMicroservice/Configurations/Kubernetes/service.yaml
- ./APIgateway/Configurations/Kubernetes/deployment.yaml
- ./APIgateway/Configurations/Kubernetes/service.yaml
- ./AuthMicroservice/AuthMicroservice/Configurations/Kubernetes/service.yaml
- ./AuthMicroservice/AuthMicroservice/Configurations/Kubernetes/deployment.yaml

namespace: default
