apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: consul-app
  name: consul-deployment
  namespace: microservice
spec:
  selector:
    matchLabels:
      app: consul-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: consul-app
    spec:
      containers:
      - name: consul
        image: consul
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
        resources: 
           requests:
                memory: "64Mi"
                cpu: "50m"
           limits:
                memory: "256Mi"
                cpu: "500m"