apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: rabbits
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    name: management
  selector:
    app: grafana-app