apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-pv
  namespace: rabbits
  labels:
    type: local
spec:
  storageClassName: rabbitmq-data-static
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/rabbitmq-data-static"