kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-data-pvc
  namespace: rabbits
spec:
  storageClassName: rabbitmq-data-static
  accessModes:
    - ReadWriteMany
  volumeName: rabbitmq-data-pv
  resources:
    requests:
      storage: 500Mi