apiVersion: v1
kind: Service
metadata:
  name: productmicroservice
spec:
  type: ClusterIP
  selector:
    app: productmicroservice-app
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  - protocol: TCP
    name: https
    port: 443
    targetPort: 443
