apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  namespace: microservice
  labels:
    type: local
spec:
  storageClassName: microservice-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/data/logs/"