kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-pvc
  namespace: microservice
spec:
  storageClassName: microservice-storage
  accessModes:
    - ReadWriteMany
  volumeName: logs-pv
  resources:
    requests:
      storage: 500Mi