apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: rabbits
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    name: management
  selector:
    app: prometheus-app