apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: grafana-app
  name: grafana-deployment
  namespace: rabbits
spec:
  selector:
    matchLabels:
      app: grafana-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources: 
           requests:
                memory: "64Mi"
                cpu: "50m"
           limits:
                memory: "256Mi"
                cpu: "500m"      
