apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbits

configMapGenerator:
- name: rabbitmq-config
  files: 
  - ./Configs/rabbitmq.conf
  - ./Configs/enabled_plugins
  - ./Configs/definitions.json
- name: prometheus-config
  files: 
  - ./Configs/prometheus.yml
  
secretGenerator:
- name: rabbit-secret
  literals:
  - RABBITMQ_ERLANG_COOKIE="MYCOOKIECOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"
  type: Opaque
 
resources:
- ./Resources/rabbit-headless-service.yaml
- ./Resources/rabbit-statefulset-dynamic.yaml
- ./Resources/rabbit-out-service.yaml
- ./Resources/Monitoring/rabbit-prometheus-service.yaml
- ./Resources/Monitoring/rabbit-prometheus-deployment.yaml
- ./Resources/Monitoring/rabbit-grafana-service.yaml
- ./Resources/Monitoring/rabbit-grafana-deployment.yaml
