version: '3.4'

services:
  apigateway:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    ports:
      - "10000:80"
      - "11000:443"
    volumes:
      - ../Content/https/:/https:ro
  productmicroservice:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    environment:
      - MICROSERVICE_HOST=productmicroservice
      - CONSUL_SERVICE_NAME=productmicroservice
    ports:
      - "10001:80"
      - "11001:443"
    volumes:
      - ../Content/https/:/https:ro
  productmicroservice2:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    environment:
      - MICROSERVICE_HOST=productmicroservice2
      - CONSUL_SERVICE_NAME=productmicroservice
    ports:
      - "10002:80"
      - "11002:443"
    volumes:
      - ../Content/https/:/https:ro
  reportmicroservice:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    environment:
      - MICROSERVICE_HOST=reportmicroservice
      - CONSUL_SERVICE_NAME=reportmicroservice
    ports:
      - "10003:80"
      - "11003:443"
    volumes:
      - ../Content/https/:/https:ro  
  reportmicroservice2:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    environment:
      - MICROSERVICE_HOST=reportmicroservice2
      - CONSUL_SERVICE_NAME=reportmicroservice
    ports:
      - "10004:80"
      - "11004:443"
    volumes:
      - ../Content/https/:/https:ro  
  reportmicroservice3:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    environment:
      - MICROSERVICE_HOST=reportmicroservice3
      - CONSUL_SERVICE_NAME=reportmicroservice
    ports:
      - "10005:80"
      - "11005:443"
    volumes:
      - ../Content/https/:/https:ro
  authmicroservice:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    ports:
      - "10006:80"
      - "11006:443"
    volumes:
      - ../Content/https/:/https:ro
  filemicroservice:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    environment:
      - MICROSERVICE_HOST=filemicroservice
      - CONSUL_SERVICE_NAME=filemicroservice      
    ports:
      - "10007:80"
      - "11007:443"
    volumes:
      - ../Content/https/:/https:ro
      - ../Content/Google/:/var/Google:ro
  filemicroservice2:
    env_file:
      - ./Configurations/.NetMicroservice/.env
    environment:
      - MICROSERVICE_HOST=filemicroservice2
      - CONSUL_SERVICE_NAME=filemicroservice
    ports:
      - "10008:80"
      - "11008:443"
    volumes:
      - ../Content/https/:/https:ro
      - ../Content/Google/:/var/Google:ro
  rabbitmqserver:
    env_file:
      - ./Configurations/RabbitMqServer/.env
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      #- ${RABBITPATH}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro
      - ${RABBITPATH}/RabbitMQServer/plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ${RABBITPATH}/RabbitMQServer/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ${RABBITPATH}/RabbitMQServer/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${RABBITPATH}/RabbitMQServer/data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmqserver 
      - ${RABBITPATH}/RabbitMQServer/logs:/var/log/rabbitmq/log
  rabbitmqnode1:
    env_file:
      - ./Configurations/RabbitMqNode1/.env
    ports:
      - "5673:5672"
      - "15673:15672"
      - "15693:15692"
    volumes:
      #- ${RABBITPATH}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro
      - ${RABBITPATH}/RabbitMQNode1/plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ${RABBITPATH}/RabbitMQNode1/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ${RABBITPATH}/RabbitMQNode1/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${RABBITPATH}/RabbitMQNode1/data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmqnode1 
      - ${RABBITPATH}/RabbitMQNode1/logs:/var/log/rabbitmq/log
  rabbitmqnode2:
    env_file:
      - ./Configurations/RabbitMqNode2/.env
    ports:
      - "5674:5672"
      - "15674:15672"
      - "15694:15692"
    volumes:
      #- ${RABBITPATH}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro
      - ${RABBITPATH}/RabbitMQNode2/plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ${RABBITPATH}/RabbitMQNode2/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ${RABBITPATH}/RabbitMQNode2/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${RABBITPATH}/RabbitMQNode2/data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmqnode2 
      - ${RABBITPATH}/RabbitMQNode2/logs:/var/log/rabbitmq/log
  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ${RABBITPATH}/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    ports:
      - "3000:3000"
  consul:
    ports:
      - "8500:8500"