version: '3.4'

services:
  apigateway:
    container_name: apigateway
    image: ${DOCKERHUBID}/apigateway:${TAG}
    build:
      context: ../APIGateway
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
  productmicroservice:
    container_name: productmicroservice
    image: ${DOCKERHUBID}/productmicroservice:${TAG}
    build:
      context: ../ProductMicroservice
      dockerfile: ProductMicroservice/Dockerfile
      args:
        ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
  reportmicroservice:
    container_name: reportmicroservice
    image: ${DOCKERHUBID}/reportmicroservice:${TAG}
    build:
      context: ../ReportMicroservice
      dockerfile: ReportMicroservice/Dockerfile
      args:
        ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}