version: '3.8'

services:
  apigateway:
    container_name: apigateway
    image: ${DOCKERHUBID}/apigateway:${TAG}
    build:
      context: ../APIGateway
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
  productmicroservice:
    container_name: productmicroservice
    image: ${DOCKERHUBID}/productmicroservice:${TAG}
    build:
      context: ../ProductMicroservice
      dockerfile: ProductMicroservice/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
  reportmicroservice:
    container_name: reportmicroservice
    image: ${DOCKERHUBID}/reportmicroservice:${TAG}
    build:
      context: ../ReportMicroservice
      dockerfile: ReportMicroservice/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
  authmicroservice:
    container_name: authmicroservice
    image: ${DOCKERHUBID}/authmicroservice:${TAG}
    build:
      context: ../AuthMicroservice
      dockerfile: AuthMicroservice/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
  rabbitmqserver:
    container_name: rabbitmqserver
    image: rabbitmq:3.8.9-management
  rabbitmqnode1:
    container_name: rabbitmqnode1
    image: rabbitmq:3.8.9-management
    depends_on:
      - "rabbitmqserver"
  rabbitmqnode2:
    container_name: rabbitmqnode2
    image: rabbitmq:3.8.9-management
    depends_on:
      - "rabbitmqserver"