version: '3.4'

services:
  apigateway:
    env_file:
        - .env
    ports:
      - "10000:80"
      - "11000:443"
    volumes:
      - ../Content/https/:/https:ro
  productmicroservice:
    env_file:
        - .env
    ports:
      - "10001:80"
      - "11001:443"
    volumes:
      - ../Content/https/:/https:ro
  reportmicroservice:
    env_file:
        - .env
    ports:
      - "10002:80"
      - "11002:443"
    volumes:
      - ../Content/https/:/https:ro  
  authmicroservice:
    env_file:
        - .env
    ports:
      - "10003:80"
      - "11003:443"
    volumes:
      - ../Content/https/:/https:ro
  rabbitmqserver:
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${RABBITPATH}/RabbitMQData/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ${RABBITPATH}/RabbitMQData/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${RABBITPATH}/RabbitMQData/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ${RABBITPATH}/RabbitMQData/logs:/var/log/rabbitmq/log