version: '3.4'

services:
  apigateway:
    env_file:
        - .env
    ports:
      - "10000:80"
      - "11000:443"
    volumes:
      - ../Content/https/:/https:ro
  productmicroservice:
    env_file:
        - .env
    ports:
      - "10001:80"
      - "11001:443"
    volumes:
      - ../Content/https/:/https:ro
  reportmicroservice:
    env_file:
        - .env
    ports:
      - "10002:80"
      - "11002:443"
    volumes:
      - ../Content/https/:/https:ro  