version: '3.8'

services:
  apigateway:
    container_name: apigateway
    image: ${DOCKERHUBID}/apigateway:${TAG}
    build:
      context: ../APIGateway
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
  productmicroservice:
    container_name: productmicroservice
    image: ${DOCKERHUBID}/productmicroservice:${TAG}
    command: ['sh', '-c', "until wget http://consul:8500/v1/status/leader; do echo waiting for consul; sleep 2; done"]
    build:
      context: ../ProductMicroservice
      dockerfile: ProductMicroservice.API/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - "consul"
  productmicroservice2:
    container_name: productmicroservice2
    image: ${DOCKERHUBID}/productmicroservice:${TAG}
    command: ['sh', '-c', "until wget http://consul:8500/v1/status/leader; do echo waiting for consul; sleep 2; done"]
    build:
      context: ../ProductMicroservice
      dockerfile: ProductMicroservice.API/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - "consul"
  reportmicroservice:
    container_name: reportmicroservice
    image: ${DOCKERHUBID}/reportmicroservice:${TAG}
    build:
      context: ../ReportMicroservice
      dockerfile: ReportMicroservice.API/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - "consul"
  reportmicroservice2:
    container_name: reportmicroservice2
    image: ${DOCKERHUBID}/reportmicroservice:${TAG}
    build:
      context: ../ReportMicroservice
      dockerfile: ReportMicroservice.API/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - "consul"
  reportmicroservice3:
    container_name: reportmicroservice3
    image: ${DOCKERHUBID}/reportmicroservice:${TAG}
    build:
      context: ../ReportMicroservice
      dockerfile: ReportMicroservice.API/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      - "consul"
  authmicroservice:
    container_name: authmicroservice
    image: ${DOCKERHUBID}/authmicroservice:${TAG}
    build:
      context: ../AuthMicroservice
      dockerfile: AuthMicroservice.API/Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
  rabbitmqserver:
    container_name: rabbitmqserver
    image: rabbitmq:3.8.9-management
  rabbitmqnode1:
    container_name: rabbitmqnode1
    image: rabbitmq:3.8.9-management
    depends_on:
      - "rabbitmqserver"
  rabbitmqnode2:
    container_name: rabbitmqnode2
    image: rabbitmq:3.8.9-management
    depends_on:
      - "rabbitmqserver"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    depends_on:
      - "rabbitmqserver"
      - "rabbitmqnode1"
      - "rabbitmqnode2"
  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - "prometheus"
  consul:
    container_name: consul1
    image: consul