apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: reportmicroservice-app
  name: reportmicroservice-pod
spec:
  selector:
    matchLabels:
      app: reportmicroservice-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: reportmicroservice-app
    spec:
      volumes:
      - name: sslcertificate
        configMap:
          name: sslconfig
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "12345"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /https/aspnetapp.pfx
        - name: ASPNETCORE_URLS
          value: https://+:443;http://+:80
        name: reportmicroservice
        image: vlogp/reportmicroservice:development
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /https/aspnetapp.pfx
          name: sslcertificate
          subPath: aspnetapp.pfx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: 
           requests:
                memory: "64Mi"
                cpu: "50m"
           limits:
                memory: "256Mi"
                cpu: "500m"      
