apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: authmicroservice-app
  name: authmicroservice-deployment
  namespace: microservice
spec:
  selector:
    matchLabels:
      app: authmicroservice-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: authmicroservice-app
    spec:
      volumes:
      - name: ssl-certificate
        configMap:
          name: ssl-config
      - name: logs-data
        persistentVolumeClaim:
          claimName: logs-pvc
      containers:
      - name: authmicroservice
        image: vlogp/authmicroservice:development
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
               name: dotnet-env-config
        volumeMounts:
        - mountPath: /https/aspnetapp.pfx
          name: ssl-certificate
          subPath: aspnetapp.pfx
        - mountPath: /app/Logs
          name: logs-data
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: 
           requests:
                memory: "64Mi"
                cpu: "50m"
           limits:
                memory: "256Mi"
                cpu: "500m"